### PR TITLE
Added functions to support getprivatekey wallet GUI endpoint

### PR DESCRIPTION
**Pull request by kmchicoine**

### CODE REVIEW

**Review by jbearer — CHANGES_REQUESTED** [review]
Can we use `state.*_keys.get(&pub_key)` and return an error if the key doesn't exist, instead of panicking?

**Comment by kmchicoine** [comment]
Sure- should those be WalletErrors, and if so, what type should I use for the freezer/auditor keys (or add new ones?)?

**Comment by jbearer** [comment]
Yep, `WalletError`, and I think you'll have to add new variants like `InvalidUserAddress { address }`

**Review by jbearer — COMMENTED** [review]
Oh sorry I missed this before but we should take the `UserAddress`, `FreezerPubKey`, and `AuditorPubKey` by reference since they aren't `Copy`

**Comment by jbearer** [comment]
After that it looks good

**Review by jbearer — APPROVED** [review]

**Pull request merged**
